### ISSUE TITLE
Please add the gun.class to the example-gun-mod

### ISSUE THREAD

**Issue by theredghostwolf** [JoshuaSkelly/delver-example-mods#11]
im not sure if there is a way right now to add new behaviour to mods, besides reusing old classes there is no compiler / scripting engine for the mods, atleast for as far as i know. would be great if that was added.

 as well as maybe a npc example added to the mod. like a dungeon enemy wielding a gun just so people get an idea of how to create their own enemies.

**Comment by joshuaskelly** [comment]
The mods are for the upcoming Update 14.
