### ISSUE TITLE
Sometimes new added armor type items just erase everything in the number group they are placed on

### ISSUE THREAD

**Issue by JavierLealCortes** [JoshuaSkelly/delver-example-mods#15]
Repro:

Using the existing default items in Delver, there are 5 groups of weapons (1-5) and 7 groups of armor items (1-7)

- Create a Mod that add new weapons to groups 1, 2, 3, 4 and 5, and then add 1 armor type item to any of the armor groups that exists. If that item is placed in the groups 1-5 it appends correctly. If it's added to the group 6 or 7 it erases everything in that group.

Temporary BAD solution:
If you add an empty weapon group 6 and an empty weapon group 7, it solves the issue and now the armor item is added correctly.
(It's a bad solution because, apparently empty groups of items crash the game if the game is trying to pick an item from that group)

**Comment by joshuaskelly** [comment]
Created an issue in the Delver repo to track this.

**Comment by joshuaskelly** [comment]
Fixed. Will be in next update.
