### ISSUE TITLE
Empty groups of items crash the game when trying to pick an item from that group

### ISSUE THREAD

**Issue by JavierLealCortes** [JoshuaSkelly/delver-example-mods#16]
Repro:

- Create a mod with a weapon group 6 and 7 but with no items in them.
- Now the game crashes sometimes when visiting the starting merchant or when entering a new floor level.

**Comment by joshuaskelly** [comment]
Created an issue in the Delver repo to track this.

**Comment by joshuaskelly** [comment]
After fixing #15 I can no longer get this to repro.
