### ISSUE TITLE
Missing UI localization strings

### ISSUE THREAD

**Issue by JavierLealCortes** [JoshuaSkelly/delver-example-mods#22]
"Show Hud", "Head Bob" and "Shadows" are missing in the localization strings.

When you pick up gold, that string is missing too (3 gold)

**Comment by joshuaskelly** [comment]
Also it looks like "Level", "XP", and "GOLD" from the inventory screen are missing as well.

**Comment by joshuaskelly** [comment]
Looks like the key for the translation strings on the following are incorrect on the Delver side:
- "of The Worm"
- "of The Arcane"
- "of The Tempest"

**Comment by joshuaskelly** [comment]
This has been fixed.
