### ISSUE TITLE
Equipping item from slot 1 makes the item you swap with disappear

### ISSUE THREAD

**Issue by JavierLealCortes** [JoshuaSkelly/delver-example-mods#23]
I remember this bug happened before but I thought you fixed it in a stream :O

## Repro Steps
1. Equip armor on your body.
2. But a piece of body armor in hotbar slot 1.
3. Activate the hotbar item in slot 1.

One of the armors disappears.

**Comment by joshuaskelly** [comment]
Created an issue on our end to track this.

**Comment by joshuaskelly** [comment]
This has been fixed.
