### ISSUE TITLE
Leveling up while wearing +health items doesn't set your health at maximum

### ISSUE THREAD

**Issue by JavierLealCortes** [JoshuaSkelly/delver-example-mods#26]
Repro:
--------------------
- Equip the ring of greater health (Armor group 7)
- Eat some food to restore your health at maximum
- Level Up.

Looks like it sets your health to your maximum base health without taking into account your items.

When you are at maximum health and you level up, you end up with less health than before.

**Comment by theredghostwolf** [comment]
same here, added my own items giving a full armor set with + 7 hp on each piece, giving ~70 hp each levelup sets you back to 8 or whatever your base is.

**Comment by joshuaskelly** [comment]
Created an issue on the Delver side of things.
