### ISSUE TITLE
End levels only connecting from one side

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#31]
When creating End sections (levels) in DelvEdit they are only accessible ingame when connected by a floor on the left side. All other sides do not work (will generate a wall).
Is this the intended behavior? If so, it is quite confusing.

**Comment by joshuaskelly** [comment]
This is by design. All of the rooms have a fixed orientation and the dungeon generator will rotate them to fit correctly. If you look at how we've built the vanilla Delver rooms, you will see the correct orientation for each room type.

**Comment by PythooonUser** [comment]
Okay. Thanks, makes sense.
