### ISSUE TITLE
Left exit of level created with DelvEdit extends to infinity

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#32]
## Summary
When creating a level in DelvEdit the left exit (seen from when started DelvEdit initially, red line) extends out of the grid region to infinity as a straight floor when entering game mode (P).

This is an example level. The level only extends to the grid boundary.
![level](https://cloud.githubusercontent.com/assets/13063023/25372264/0225c2be-2995-11e7-8d3b-288777914a8a.jpg)

When entering game mode, notice the minimap displays the infinite floor.
![level_ingame](https://cloud.githubusercontent.com/assets/13063023/25372269/0b075208-2995-11e7-8171-be310f5ac284.jpg)

When using the level in Delver it is not accessible because a wall is spawned (may be due to this or not), although the exits seem to be placed correctly.

The same is happening with the TriIntersection example in /dungeon-section-basic/generator/Template.

**Comment by joshuaskelly** [comment]
Is this behavior limited to DelvEdit? Or does it also reproduce in Delver as well?

**Comment by PythooonUser** [comment]
I created another example level and upped the spawn probability to 1, but couldn't manage to see the level ingame yet.

**Comment by PythooonUser** [comment]
I guess this is fixed with 1.0 now. I will close this issue.
