### ISSUE TITLE
Stairs Up / Stairs Down Marker not distinguishable on map

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#33]
## Summary
The stairs down/up marker (green squares) are not distinguishable. Maybe replace them with small icons like the ones in DelvEdit? Or is this by-design?

![20170429191343_1_](https://cloud.githubusercontent.com/assets/13063023/25557548/31a84458-2d14-11e7-8223-5cfc81f0a33d.jpg)

**Comment by joshuaskelly** [comment]
Created an issue on the Delver side of things.
