### ISSUE TITLE
Level '???' is incorrectly displayed on map

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#34]
Parts of the non-terrain regions of the map of level '???' are not displayed on the map.

![20170429191509_1](https://cloud.githubusercontent.com/assets/13063023/25557576/975e56ac-2d14-11e7-9142-fb00f236f062.jpg)

**Comment by joshuaskelly** [comment]
Created an issue on the Delver side of things.
