### ISSUE TITLE
Not able to sell items at merchants

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#35]
## Feature Request
Leaving items behind hurts my RPG heart^^
Maybe merchants could be able to buy stuff from the player in the future?

![20170429191545_1](https://cloud.githubusercontent.com/assets/13063023/25557587/dd42390e-2d14-11e7-93f7-2b59c4b31fad.jpg)

**Comment by joshuaskelly** [comment]
This is by design. The ability to sell items introduces undesirable player behavior.
