### ISSUE TITLE
Fog of war over water does not disappear

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#36]
## Summary
Maybe it's a map issue (player didn't reach the desired region), but parts of the water in this level remain hidden under the fog of war, even when standing at the position.

![20170429192757_1_](https://cloud.githubusercontent.com/assets/13063023/25557629/adeb38d0-2d15-11e7-9b80-02dccd4e7f2a.jpg)

**Comment by joshuaskelly** [comment]
Created issue on Delver side.
