### ISSUE TITLE
Enchanted Hunters Bow does not show additional damage

### ISSUE THREAD

**Issue by PythooonUser** [JoshuaSkelly/delver-example-mods#37]
## Summary
Enchanted Hunter's Bow does not show the type of additional damage it does. Here it is fire damage (red particle effect on arrows).
Maybe this information can be derived from the name color. But maybe this information is just not supplied, because the Bow only has a certain probability to trigger the fire effect?

![20170429193325_1](https://cloud.githubusercontent.com/assets/13063023/25557632/cab42896-2d15-11e7-82da-7a78f9c1f9f7.jpg)

**Comment by joshuaskelly** [comment]
Created an issue on the Delver side of things.
