### ISSUE TITLE
Overworld test

### ISSUE THREAD

**Issue by SHADOWELITE7** [JoshuaSkelly/delver-example-mods#46]
When I pushed `Subscribe` it doesn't install the mod

**Comment by PythooonUser** [comment]
Hello @SHADOWELITE7. Thanks for trying out the mod.

I could reproduce the issue you had with the subscribe button in Steam.
The current workaround is to manually download the mod from this repo and put it under `Mods/` in the root folder of Delver.

Then it works upon creating a new save game and finishing the tutorial level.

**Comment by SHADOWELITE7** [comment]
thx

**Comment by PythooonUser** [comment]
@joshuaskelly The issue can be closed because the question could be answered.
